{
	"version": 1665877810,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/sprite-sheet2.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/left1-sheet0.png",
		"images/right1-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite6-sheet1.png",
		"images/sprite4-sheet0.png",
		"images/sprite4-sheet1.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/menu-sheet0.png",
		"images/resume-sheet0.png",
		"images/kl-sheet0.png",
		"images/pl-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite16-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/sprite18-sheet0.png",
		"media/dry_fire.ogg",
		"media/load.ogg",
		"media/kick.ogg",
		"media/music 1.ogg",
		"media/punch.ogg",
		"media/woosh 1.ogg",
		"media/woosh 2.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}